[package]
name = "data-generator-cli"
version = "0.1.0"
authors = ["Tahar <tntmeijs@gmail.com>"]
edition = "2018"
description = "Command-line utility program to generate demo files"
license = "MIT"
repository = "https://github.com/tntmeijs/rust-wasm-experiments"

[dependencies]
rand = "0.8.3"
